// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgIPMJsoMOAbCy3DZfbEZqwGwolhNijIk',
    appId: '1:389066436510:web:1a6184f70cac18287bf08f',
    messagingSenderId: '389066436510',
    projectId: 'fcm-lab-6',
    authDomain: 'fcm-lab-6.firebaseapp.com',
    storageBucket: 'fcm-lab-6.firebasestorage.app',
    measurementId: 'G-FR94Y22Y3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn04j057bQMb6LUh0E-ohQArSKXV52zHw',
    appId: '1:389066436510:android:fc5a1b84c8d1b6877bf08f',
    messagingSenderId: '389066436510',
    projectId: 'fcm-lab-6',
    storageBucket: 'fcm-lab-6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Zw5NaIL7oloGB-LA98FTkQQ45Trb1EA',
    appId: '1:389066436510:ios:22a995465b2e0dd37bf08f',
    messagingSenderId: '389066436510',
    projectId: 'fcm-lab-6',
    storageBucket: 'fcm-lab-6.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Zw5NaIL7oloGB-LA98FTkQQ45Trb1EA',
    appId: '1:389066436510:ios:22a995465b2e0dd37bf08f',
    messagingSenderId: '389066436510',
    projectId: 'fcm-lab-6',
    storageBucket: 'fcm-lab-6.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgIPMJsoMOAbCy3DZfbEZqwGwolhNijIk',
    appId: '1:389066436510:web:a148b25a1fa053907bf08f',
    messagingSenderId: '389066436510',
    projectId: 'fcm-lab-6',
    authDomain: 'fcm-lab-6.firebaseapp.com',
    storageBucket: 'fcm-lab-6.firebasestorage.app',
    measurementId: 'G-MGQXSMDP88',
  );
}
